### ISSUE TITLE
emqx_v4 - parsing incomplete

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/brokers#3]
We are not able to launch emqx_v4 getting `Syntax error in /opt/emqx/etc/emqx.conf after line 11 column 1, parsing incomplete`

![image](https://user-images.githubusercontent.com/73840223/222061861-d3ad2f23-c2dd-4511-bd79-4087838463b2.png)

Steps to reproduce:
1. clone https://github.com/hummingbot/brokers
2. Go to compose/emqx_v4 then run `launch.sh`

**Comment by klpanagi** [comment]
@rapcmia This error is due to previously running the v5 version of emqx and thus the `emqx-data` volume contains files not supported by v4.

Though, I will change the volume names so that cannot be messed up.
