### ISSUE TITLE
MQTT Bridge failed to connect to the broker

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/brokers#8]
When starting the hummingbot client with mqtt_autostart enabled without a running hummingbot broker, the expected behavior is that it would return an error of:

![image](https://github.com/hummingbot/brokers/assets/73840223/b58bff60-5d3b-46cb-8d27-8d67971924de)

When starting the hummingbot broker while the client is running, you would get a different behavior where the heartbeat thread ended yet still getting `Failed to connect MQTT Bridge: Connection timed out after 30.0 seconds. Retrying in 10.0 seconds.`

![image](https://github.com/hummingbot/brokers/assets/73840223/68f02260-1f1b-4c93-9591-5363c1baf7f4)

Would be possible to stop the prompt of failed to connect and recognize that a connection has been established from client and mqtt like gateway?

**Comment by rapcmia** [comment]
Workaround:  When hummingbot broker connection is established, relaunch hummingbot client

**Comment by klpanagi** [comment]
Sorry guys, I was AFK for some time.
I will have a look on this one. The broker client should be able to reconnect without exiting hummingbot

**Comment by rapcmia** [comment]
No worries, thanks for checking it @klpanagi 🙇🏼

**Comment by rapcmia** [comment]
Hi @klpanagi good day to you, just want to check for update if we can have a PR for fix? if not possible we can open a community bounty as well for the fix. Thank you 🙇🏼

**Comment by klpanagi** [comment]
Hello @rapcmia I am currently working on a fix. This should be a PR on the hummingbot/hummingbot codebase.
Would appreciate a bounty assigned to me for this :)

**Comment by nikspz** [comment]
Bounty Title: Fix for Broker Issue with mqtt_autostart Enabled

Description:
There is a known issue with the broker when the client is started with mqtt_autostart enabled, especially in conjunction with the dashboard. The objective is to address and resolve this issue to enhance the overall functionality.

Requirements:
Investigate the broker behavior when the client is initiated with mqtt_autostart.
Identify and fix the issue causing complications, especially in coordination with the dashboard.
Ensure that the broker functions seamlessly, providing a stable and reliable experience.

Reward: 50,000 HBOT

Submission Guidelines:
Submit a detailed explanation of the changes made, including any relevant code modifications. Provide steps to reproduce the previous issue and demonstrate that the proposed fix resolves it effectively.

Contact:
For any clarifications or updates, reach out to @rapcmia or @nikspz 

Note:
This bounty is aimed at improving the user experience and functionality of the broker, particularly when the client is started with mqtt_autostart enabled. The Hummingbot community values your contributions in making the platform more robust and user-friendly.

**Comment by nikspz** [comment]
Assigned to @klpanagi , please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by klpanagi** [comment]
Hello @nikspz .

I have already prepare a fix for this: https://github.com/klpanagi/hummingbot/commit/f803bb9ead4a0f5e417c70c5c9a17dde007848c6

I will create the PR today.

**Comment by klpanagi** [comment]
PR created: https://github.com/hummingbot/hummingbot/pull/6704

**Comment by rapcmia** [comment]
Fix has been deployed on development and will be part of release 1.23.0

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @klpanagi . The fix has been deployed on development branch and hummingbot version 1.23.0.
